global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:7071']

  - job_name: 'coupon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coupon-service:7072']
  
  - job_name: 'point-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['point-service:7073']
  
  - job_name: 'timesale-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['timesale-service:7074']
  
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:7070']
      
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']