# config.yaml
logging:
  filepath: "logs/app.log"
  level: "info"

postgres:
  url: "postgres://postgres:my-secret-pw@localhost:5432/coupon_db?sslmode=disable"
  max_conns: 50
  min_conns: 5
  max_conn_lifetime: 1h
  health_check_period: 2m

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
