# config.yaml
server:
  name: gocoupon-service
  host: gocoupon-service
  port: 8080

logging:
  filepath: "logs/app.log"
  level: "info"

postgres:
  url: "postgres://postgres:my-secret-pw@postgres:5432/coupon_db?sslmode=disable"
  max_conns: 50
  min_conns: 5
  max_conn_lifetime: 1h
  health_check_period: 2m

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0

kafka:
  brokers:
    - "kafka:9092"
  group_id: "gocoupon-service"

metric:
  host: gocoupon-service
  port: 7070  

zipkin:
  url: http://zipkin:9411/api/v2/spans