global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'gocoupon-service'
    metrics_path: '/metrics/prometheus'
    static_configs:
      # - targets: ['host.docker.internal:7070']
      - targets: ['gocoupon-service:7070']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']