basePath: /api/v1
definitions:
  coupon.Coupon:
    properties:
      code:
        type: string
      couponPolicy:
        $ref: '#/definitions/coupon.CouponPolicy'
      couponPolicyId:
        type: string
      createdAt:
        type: string
      id:
        type: string
      orderId:
        type: string
      status:
        $ref: '#/definitions/coupon.CouponStatus'
      updatedAt:
        type: string
      usedAt:
        type: string
      userId:
        type: string
    type: object
  coupon.CouponPolicy:
    properties:
      code:
        type: string
      coupons:
        items:
          $ref: '#/definitions/coupon.Coupon'
        type: array
      createdAt:
        type: string
      description:
        type: string
      discountType:
        $ref: '#/definitions/coupon.DiscountType'
      discountValue:
        type: integer
      endTime:
        type: string
      id:
        type: string
      maximumDiscountAmount:
        type: integer
      minimumOrderAmount:
        type: integer
      name:
        type: string
      startTime:
        type: string
      totalQuantity:
        type: integer
      updatedAt:
        type: string
    type: object
  coupon.CouponStatus:
    enum:
    - AVAILABLE
    - USED
    - EXPIRED
    - CANCELED
    type: string
    x-enum-varnames:
    - CouponStatusAvailable
    - CouponStatusUsed
    - CouponStatusExpired
    - CouponStatusCanceled
  coupon.DiscountType:
    enum:
    - FIXED_AMOUNT
    - PERCENTAGE
    type: string
    x-enum-varnames:
    - DiscountTypeFixedAmount
    - DiscountTypePercentage
info:
  contact: {}
  description: Coupon API V1
  title: Coupon API V1
  version: "1.0"
paths:
  /couponPolicies:
    get:
      description: Get coupon policies by ID, code, or name. If no parameters are
        provided, return all coupon policies.
      parameters:
      - description: Coupon Policy ID
        in: query
        name: id
        type: string
      - description: Coupon Code
        in: query
        name: code
        type: string
      - description: Coupon Name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/coupon.CouponPolicy'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search coupon policies (by ID, Code, Name, or all)
      tags:
      - Coupon Policy
  /couponPolicies/dummy:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/coupon.CouponPolicy'
            type: array
      summary: Create dummy coupon policies
      tags:
      - Coupon Policy
  /coupons:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: List coupons
      tags:
      - Coupons
swagger: "2.0"
