auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 20971520  

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB
  allow_structured_metadata: false 

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

table_manager:
  retention_deletes_enabled: true
  retention_period: 7d

schema_config:
  configs:
    - from: 2025-01-01        # Start date for this schema configuration
      store: tsdb              # Use TSDB (Time Series Database) storage
      object_store: filesystem # Store data on local filesystem
      schema: v13              # Schema version
      index:
        prefix: index_         # Prefix for index files
        period: 24h            # Create a new index every 24 hours