app:
  name: "coupon-service"
  host: "localhost"
  port: 8080
  env: "development"
  metric:
    host: "localhost"
    port: 7070

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "my-secret-pw"
  dbname: "coupon_db"
  sslmode: "disable"
  # max_open_conns: 10
  # max_idle_conns: 5
  # conn_max_lifetime: "1h"
  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: "30m"
  
redis:
  host: "localhost"
  port: 6379
  user: "redis"
  password: ""
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  groupid: "coupon-service-group"

logger:
  level: "info"
  filepath: "logs/app.log"

otel:
  host: "localhost"
  port: 4317