app:
  name: "account-service"
  env: "development"

http:
  host: "127.0.0.1"
  port: 8081

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "my-secret-pw"
  dbname: "account_db"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

jwt:
  secret_key: "S3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3y"
  expires_in: "24h"

logger:
  level: "info"
  filepath: "logs/app.log"

consul:
  address: "localhost:8500"
  wait_time: "15s"